name: Spotify Discover Weekly Backup

on:
  schedule:
    - cron: "0 9 * * 1" # Runs every Monday at 9 AM UTC
  workflow_dispatch: # Allows manual triggering of the workflow if needed

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Run Spotify Backup Script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          DISCOVER_WEEKLY_NAME: ${{ secrets.DISCOVER_WEEKLY_NAME }}
          ARCHIVE_PLAYLIST_NAME: ${{ secrets.ARCHIVE_PLAYLIST_NAME }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: |
          . venv/bin/activate
          python weekly_backup.py
